# Generated by Django 5.2.7 on 2025-10-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.IntegerField(max_length=2),
        ),
    ]
