# Generated by Django 5.2.7 on 2025-10-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='detail',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.IntegerField(),
        ),
    ]
